### PR TITLE
add more microphysics params for EDMF calibration

### PR DESCRIPTION
**Pull request by trontrytel**
I want to try more things on the EDMF calibration side. Therefore I need more parameters. 

Will do a patch release after this lands.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Aren't these breaking changes because the name is changing? This is non-breaking if we just add new parameters. If you know for sure that this parameter is not used anywhere, then fine with me to make things move faster.

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
> Aren't these breaking changes because the name is changing? This is non-breaking if we just add new parameters. If you know for sure that this parameter is not used anywhere, then fine with me to make things move faster.

Oh damn. You are right. I will keep the name for one of them the same so that I can keep it as a patch release.

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
@charleskawczynski - should be good now?

**Review by charleskawczynski — APPROVED** [review]

**Pull request merged**
