### PR TITLE
correct doi for abifm desert dust params

### PR DESCRIPTION
**Pull request by amylu00**
## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by amylu00** [comment]
> Do you need to change the parameter names? This will need to be a breaking release

Yes, but since it's only used in the gpu/perf/unit tests right now Anna and I were hoping to just do a version bump. Is that no good?

**Comment by nefrathenrici** [comment]
That's fair enough! If they are only used in one place it should be fine.

**Review by nefrathenrici — APPROVED** [review]

**Comment by trontrytel** [comment]
But we still need to bump the patch version in the `Project.toml` file. `version = "0.8.5"` -> `version = "0.8.6"`

Those parameters are only used in CloudMicrophysics.jl tests. The packages that use CloudMicrophysics.jl don't use those functions. So I vote to do it as a patch release. We will fix the CM.jl tests quickly and noone will notce

**Review by trontrytel — APPROVED** [review]

**Comment by nefrathenrici** [comment]
I will need a patch release for #165 as well so we could bundle the changes together.

**Pull request merged**
