### PR TITLE
Update minor version

### PR DESCRIPTION
**Pull request by akshaysridhar**
Update to v0.7.7
	modified:   Project.toml

### CODE REVIEW

**Comment by nefrathenrici** [comment]
I just updated the [patch version](https://github.com/CliMA/CLIMAParameters.jl/commit/79a42521ba68b78115543e0cb1f15e858bd1df7d), are there other changes that require a new release?

**Comment by akshaysridhar** [comment]
> I just updated the [patch version](https://github.com/CliMA/CLIMAParameters.jl/commit/79a42521ba68b78115543e0cb1f15e858bd1df7d), are there other changes that require a new release?

Nope - thanks!

**Comment by akshaysridhar** [comment]
There will be additional changes in the next couple of days related to the SURF work that might require a patch release.

**Review by nefrathenrici — APPROVED** [review]
I opened this again, since I assume you want to bump the version now @akshaysridhar

**Comment by akshaysridhar** [comment]
cc @wilsonduan10 @LenkaNovak

**Pull request merged**
