### PR TITLE
Add more parameters, bump major version

### PR DESCRIPTION
**Pull request by trontrytel**
# PULL REQUEST

## Purpose and Content
I need more parameters in CloudMicrophysics.jl and TurbulenceConvection.jl

Not sure if this is the correct workflow. I thought one of the benefits of the new way of handling parameters is that I would not have to open PRs to repos different than the one that needs the parameters? 

This is also a breaking change because I need to change one parameter name.

### CODE REVIEW

**Review by odunbar — COMMENTED** [review]
LGTM, 

RE workflow, If parameters are needed to be called in across multiple repositories and there is a sensible default value you will typically be using, then it makes sense to define this value here. If however you are still prototyping, if parameters don't have sensible defaults, or if they are only within some corner of the code, e.g. needed for a single option of some parameterization, then you can just define them within your local experiment override files (which don't require communication with `ClimaParameters.jl`).

**Review by odunbar — APPROVED** [review]

**Comment by charleskawczynski** [comment]
This can be a patch update! (also, `(x.y.z) = (major.minor.patch)`)

**Comment by trontrytel** [comment]
I don't think its a patch update since I changed a name of one of the parameters

**Comment by charleskawczynski** [comment]
> I don't think its a patch update since I changed a name of one of the parameters

It is so much easier to do a patch release, can we just not rename the parameter?

**Comment by trontrytel** [comment]
The new name is the correct one and the old one is misleading. I'll change it back to the misleading one because I know how much work it would be to do a major release here. 

I thought that our decentralised approach to parameters would prevent us from having to make such choices. Seems like this is not the case. The alternative would be to delete those parameters from here and add them locally in TC.jl. But since 3 of them are already defined here that would also be a breaking change...

**Pull request merged**
